language: node_js
node_js:
  - "stable"
env:
global:
  - export NODE_ENV=test
services:
  - postgresql
cache:
  directories: 
    - "node_modules"
before_install:
  - npm install
  - npm install coveralls
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - "nyc npm test"
after_success:
- npm run coverage